# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20171010_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='user_id',
            new_name='user',
        ),
    ]
