# Generated by Django 2.2 on 2019-10-15 13:08

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_bannercourse_course_courseresource_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情'),
        ),
    ]
