# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171010_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
