# Generated by Django 2.2 on 2019-10-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191014_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='生日'),
        ),
    ]
