# Generated by Django 2.2 on 2019-10-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191014_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
