# Generated by Django 2.2 on 2019-10-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20171010_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecomments',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecomments',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAsk',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
        migrations.DeleteModel(
            name='CourseComments',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
