# Generated by Django 2.2 on 2019-10-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20191013_0951'),
        ('organizations', '0006_courseorg_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='org',
        ),
        migrations.DeleteModel(
            name='CityDict',
        ),
        migrations.DeleteModel(
            name='CourseOrg',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
